//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviationManager.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviationManager.Lang.language_de", typeof(language_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string ladd {
            get {
                return ResourceManager.GetString("ladd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation erstellen.
        /// </summary>
        internal static string laddDeviation {
            get {
                return ResourceManager.GetString("laddDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Identifikationsmethode.
        /// </summary>
        internal static string lalternativeIdMethod {
            get {
                return ResourceManager.GetString("lalternativeIdMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe.
        /// </summary>
        internal static string lapprovement {
            get {
                return ResourceManager.GetString("lapprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        internal static string lclose {
            get {
                return ResourceManager.GetString("lclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation schließen.
        /// </summary>
        internal static string lcloseDeviation {
            get {
                return ResourceManager.GetString("lcloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt in.
        /// </summary>
        internal static string lcreatedIn {
            get {
                return ResourceManager.GetString("lcreatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string ldate {
            get {
                return ResourceManager.GetString("ldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 1.
        /// </summary>
        internal static string ldate1 {
            get {
                return ResourceManager.GetString("ldate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 2.
        /// </summary>
        internal static string ldate2 {
            get {
                return ResourceManager.GetString("ldate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string ldateCreation {
            get {
                return ResourceManager.GetString("ldateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to löschen.
        /// </summary>
        internal static string ldelete {
            get {
                return ResourceManager.GetString("ldelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string ldescription {
            get {
                return ResourceManager.GetString("ldescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaillierte Beschreibung der Abweichung.
        /// </summary>
        internal static string ldetailDescOfDev {
            get {
                return ResourceManager.GetString("ldetailDescOfDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaillierte Anfragebedingungen.
        /// </summary>
        internal static string ldetailRequestCondition {
            get {
                return ResourceManager.GetString("ldetailRequestCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen der Abweichung.
        /// </summary>
        internal static string lDeviationInfo {
            get {
                return ResourceManager.GetString("lDeviationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichungliste.
        /// </summary>
        internal static string ldeviationList {
            get {
                return ResourceManager.GetString("ldeviationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung Nu..
        /// </summary>
        internal static string ldeviationNo {
            get {
                return ResourceManager.GetString("ldeviationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art der Abweichung.
        /// </summary>
        internal static string ldeviationType {
            get {
                return ResourceManager.GetString("ldeviationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ldowload {
            get {
                return ResourceManager.GetString("ldowload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation überarbeiten.
        /// </summary>
        internal static string leditDeviation {
            get {
                return ResourceManager.GetString("leditDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation filtern.
        /// </summary>
        internal static string lfilterDeviation {
            get {
                return ResourceManager.GetString("lfilterDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlage.
        /// </summary>
        internal static string lmachine {
            get {
                return ResourceManager.GetString("lmachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Abweichung.
        /// </summary>
        internal static string lnewDeviation {
            get {
                return ResourceManager.GetString("lnewDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere (Optional).
        /// </summary>
        internal static string loptional {
            get {
                return ResourceManager.GetString("loptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere.
        /// </summary>
        internal static string lothers {
            get {
                return ResourceManager.GetString("lothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Regionaler Qualitätsdirektor: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox1 {
            get {
                return ResourceManager.GetString("lothersBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Produktengineering: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox2 {
            get {
                return ResourceManager.GetString("lothersBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Produktengineering: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox3 {
            get {
                return ResourceManager.GetString("lothersBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Kunde: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox4 {
            get {
                return ResourceManager.GetString("lothersBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginn (der Abweichung).
        /// </summary>
        internal static string lperiodBegin {
            get {
                return ResourceManager.GetString("lperiodBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichungsdauer.
        /// </summary>
        internal static string lperiodDevation {
            get {
                return ResourceManager.GetString("lperiodDevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende (der Abweichung).
        /// </summary>
        internal static string lperiodEnd {
            get {
                return ResourceManager.GetString("lperiodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string lposition {
            get {
                return ResourceManager.GetString("lposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausdrucken.
        /// </summary>
        internal static string lprint {
            get {
                return ResourceManager.GetString("lprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string lproduct {
            get {
                return ResourceManager.GetString("lproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref.
        /// </summary>
        internal static string lref {
            get {
                return ResourceManager.GetString("lref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe erinnern.
        /// </summary>
        internal static string lremindGroup {
            get {
                return ResourceManager.GetString("lremindGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfrage genehmigt.
        /// </summary>
        internal static string lrequestApproved {
            get {
                return ResourceManager.GetString("lrequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angefragt von.
        /// </summary>
        internal static string lrequestedBy {
            get {
                return ResourceManager.GetString("lrequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfrage abgelehnt.
        /// </summary>
        internal static string lrequestedRejected {
            get {
                return ResourceManager.GetString("lrequestedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risikokategorie.
        /// </summary>
        internal static string lriskCategory {
            get {
                return ResourceManager.GetString("lriskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string lsave {
            get {
                return ResourceManager.GetString("lsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigen.
        /// </summary>
        internal static string lshow {
            get {
                return ResourceManager.GetString("lshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation anzeigen.
        /// </summary>
        internal static string lshowDeviation {
            get {
                return ResourceManager.GetString("lshowDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterschrift.
        /// </summary>
        internal static string lsignature {
            get {
                return ResourceManager.GetString("lsignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sollvorgabe.
        /// </summary>
        internal static string lstandardCondition {
            get {
                return ResourceManager.GetString("lstandardCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lupdate {
            get {
                return ResourceManager.GetString("lupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutze alle Angaben.
        /// </summary>
        internal static string luseAllInputs {
            get {
                return ResourceManager.GetString("luseAllInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warum.
        /// </summary>
        internal static string lwhy {
            get {
                return ResourceManager.GetString("lwhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5  Why um die Ursache des Problems zu finden bzw. aufzuzeigen.
        /// </summary>
        internal static string lwhyBox {
            get {
                return ResourceManager.GetString("lwhyBox", resourceCulture);
            }
        }
    }
}
