//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviationManager.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviationManager.Lang.language_en", typeof(language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ladd {
            get {
                return ResourceManager.GetString("ladd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvement.
        /// </summary>
        internal static string lapprovement {
            get {
                return ResourceManager.GetString("lapprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ldate {
            get {
                return ResourceManager.GetString("ldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ldateCreation {
            get {
                return ResourceManager.GetString("ldateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ldelete {
            get {
                return ResourceManager.GetString("ldelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ldescription {
            get {
                return ResourceManager.GetString("ldescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Description of Deviation.
        /// </summary>
        internal static string ldetailDescOfDev {
            get {
                return ResourceManager.GetString("ldetailDescOfDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation Infos.
        /// </summary>
        internal static string lDeviationInfo {
            get {
                return ResourceManager.GetString("lDeviationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation List.
        /// </summary>
        internal static string ldeviationList {
            get {
                return ResourceManager.GetString("ldeviationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation No.
        /// </summary>
        internal static string ldeviationNo {
            get {
                return ResourceManager.GetString("ldeviationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation Type.
        /// </summary>
        internal static string ldeviationType {
            get {
                return ResourceManager.GetString("ldeviationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ldowload {
            get {
                return ResourceManager.GetString("ldowload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string lmachine {
            get {
                return ResourceManager.GetString("lmachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deviation.
        /// </summary>
        internal static string lnewDeviation {
            get {
                return ResourceManager.GetString("lnewDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other( Optional).
        /// </summary>
        internal static string loptional {
            get {
                return ResourceManager.GetString("loptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Begin .
        /// </summary>
        internal static string lperiodBegin {
            get {
                return ResourceManager.GetString("lperiodBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation Period.
        /// </summary>
        internal static string lperiodDevation {
            get {
                return ResourceManager.GetString("lperiodDevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period End.
        /// </summary>
        internal static string lperiodEnd {
            get {
                return ResourceManager.GetString("lperiodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string lposition {
            get {
                return ResourceManager.GetString("lposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string lproduct {
            get {
                return ResourceManager.GetString("lproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Approved.
        /// </summary>
        internal static string lrequestApproved {
            get {
                return ResourceManager.GetString("lrequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By.
        /// </summary>
        internal static string lrequestedBy {
            get {
                return ResourceManager.GetString("lrequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Rejeceted.
        /// </summary>
        internal static string lrequestedRejected {
            get {
                return ResourceManager.GetString("lrequestedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Category.
        /// </summary>
        internal static string lriskCategory {
            get {
                return ResourceManager.GetString("lriskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string lshow {
            get {
                return ResourceManager.GetString("lshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string lsignature {
            get {
                return ResourceManager.GetString("lsignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standad Condition.
        /// </summary>
        internal static string lstandardCondition {
            get {
                return ResourceManager.GetString("lstandardCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lupdate {
            get {
                return ResourceManager.GetString("lupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why.
        /// </summary>
        internal static string lwhy {
            get {
                return ResourceManager.GetString("lwhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Why to schow reason change for deviation.
        /// </summary>
        internal static string lwhyBox {
            get {
                return ResourceManager.GetString("lwhyBox", resourceCulture);
            }
        }
    }
}
