//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviationManager.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviationManager.Lang.language_de", typeof(language_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Failed..
        /// </summary>
        internal static string actionFailed {
            get {
                return ResourceManager.GetString("actionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry !, You Can Not Approve And Reject At The Same Time!!.
        /// </summary>
        internal static string alertApprovedRejected {
            get {
                return ResourceManager.GetString("alertApprovedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Deviation Means You Will Not Be Able Later To Make Any Change On It, Are You Sure You Wish To Make This Action ?.
        /// </summary>
        internal static string alertCloseDeviation {
            get {
                return ResourceManager.GetString("alertCloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are Sure, You Wish to Delete This Attachment ?.
        /// </summary>
        internal static string alertDeleteAttachment {
            get {
                return ResourceManager.GetString("alertDeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Make This Action Now, You Schould First Save The Deviation !.
        /// </summary>
        internal static string alertSaveDeviationFirst {
            get {
                return ResourceManager.GetString("alertSaveDeviationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Approvement Was Succesfuly Done !.
        /// </summary>
        internal static string approvementDone {
            get {
                return ResourceManager.GetString("approvementDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose a Deviation Before makimg this Action!.
        /// </summary>
        internal static string chooseDeviation {
            get {
                return ResourceManager.GetString("chooseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Was Successfuly Added.
        /// </summary>
        internal static string deviationAdded {
            get {
                return ResourceManager.GetString("deviationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Make Any Change On This Item Because Its Already Closed !.
        /// </summary>
        internal static string deviationAlreadyClosed {
            get {
                return ResourceManager.GetString("deviationAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Period Has Not Valid !, The Input &lt;&lt;P.Second date&gt;&gt; Must Be Bigger Than the Input &lt;&lt;P.First date&gt;&gt;.
        /// </summary>
        internal static string deviationNegativePeriod {
            get {
                return ResourceManager.GetString("deviationNegativePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Dos Not Exist..
        /// </summary>
        internal static string deviationNotExist {
            get {
                return ResourceManager.GetString("deviationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Period Has Not To Be Null!, You Can Choose Different Dates To Avoid This..
        /// </summary>
        internal static string deviationPeriodNull {
            get {
                return ResourceManager.GetString("deviationPeriodNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Was Successfly Updated..
        /// </summary>
        internal static string deviationupdated {
            get {
                return ResourceManager.GetString("deviationupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deviation Was Succesfuly Closed..
        /// </summary>
        internal static string deviationWasClosed {
            get {
                return ResourceManager.GetString("deviationWasClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Email has been sent !.
        /// </summary>
        internal static string emailSent {
            get {
                return ResourceManager.GetString("emailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, The Deviation Cloud Not Be Closed..
        /// </summary>
        internal static string errorCloseDeviation {
            get {
                return ResourceManager.GetString("errorCloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros, The Email Was Not Sent Try Again !.
        /// </summary>
        internal static string errorSendEmail {
            get {
                return ResourceManager.GetString("errorSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This File Dos Not Exist Any More!..
        /// </summary>
        internal static string fileNotExist {
            get {
                return ResourceManager.GetString("fileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Had Been Removed From The List!..
        /// </summary>
        internal static string fileRemovedFromList {
            get {
                return ResourceManager.GetString("fileRemovedFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Form Inputs Are Not Valid !.
        /// </summary>
        internal static string formInputsNotValid {
            get {
                return ResourceManager.GetString("formInputsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs Are Missing !!.
        /// </summary>
        internal static string inputsMissing {
            get {
                return ResourceManager.GetString("inputsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Inputs Are Required ..
        /// </summary>
        internal static string inputsRequired {
            get {
                return ResourceManager.GetString("inputsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string ladd {
            get {
                return ResourceManager.GetString("ladd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung erstellen.
        /// </summary>
        internal static string laddDeviation {
            get {
                return ResourceManager.GetString("laddDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle eine Abweichungserlaubnis.
        /// </summary>
        internal static string laddNewDeviation {
            get {
                return ResourceManager.GetString("laddNewDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhang.
        /// </summary>
        internal static string lalternativeIdMethod {
            get {
                return ResourceManager.GetString("lalternativeIdMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe.
        /// </summary>
        internal static string lapprovement {
            get {
                return ResourceManager.GetString("lapprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung.
        /// </summary>
        internal static string lartabweichung {
            get {
                return ResourceManager.GetString("lartabweichung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        internal static string lclose {
            get {
                return ResourceManager.GetString("lclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung schließen.
        /// </summary>
        internal static string lcloseDeviation {
            get {
                return ResourceManager.GetString("lcloseDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt am.
        /// </summary>
        internal static string lcreatedIn {
            get {
                return ResourceManager.GetString("lcreatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string ldate {
            get {
                return ResourceManager.GetString("ldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum von.
        /// </summary>
        internal static string ldate1 {
            get {
                return ResourceManager.GetString("ldate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum bis.
        /// </summary>
        internal static string ldate2 {
            get {
                return ResourceManager.GetString("ldate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string ldateCreation {
            get {
                return ResourceManager.GetString("ldateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to löschen.
        /// </summary>
        internal static string ldelete {
            get {
                return ResourceManager.GetString("ldelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere (optional).
        /// </summary>
        internal static string ldescription {
            get {
                return ResourceManager.GetString("ldescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaillierte Beschreibung der Abweichung.
        /// </summary>
        internal static string ldetailDescOfDev {
            get {
                return ResourceManager.GetString("ldetailDescOfDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung Istzustand.
        /// </summary>
        internal static string ldetailRequestCondition {
            get {
                return ResourceManager.GetString("ldetailRequestCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung Suchmaske.
        /// </summary>
        internal static string ldeviationFilterBox {
            get {
                return ResourceManager.GetString("ldeviationFilterBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen zur Abweichung.
        /// </summary>
        internal static string lDeviationInfo {
            get {
                return ResourceManager.GetString("lDeviationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichungsliste.
        /// </summary>
        internal static string ldeviationList {
            get {
                return ResourceManager.GetString("ldeviationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung Nr..
        /// </summary>
        internal static string ldeviationNo {
            get {
                return ResourceManager.GetString("ldeviationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art der.
        /// </summary>
        internal static string ldeviationType {
            get {
                return ResourceManager.GetString("ldeviationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ldowload {
            get {
                return ResourceManager.GetString("ldowload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ldowonloadToolTip {
            get {
                return ResourceManager.GetString("ldowonloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung überarbeiten.
        /// </summary>
        internal static string leditDeviation {
            get {
                return ResourceManager.GetString("leditDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung filtern.
        /// </summary>
        internal static string lfilterDeviation {
            get {
                return ResourceManager.GetString("lfilterDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlage.
        /// </summary>
        internal static string lmachine {
            get {
                return ResourceManager.GetString("lmachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lname {
            get {
                return ResourceManager.GetString("lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Abweichung.
        /// </summary>
        internal static string lnewDeviation {
            get {
                return ResourceManager.GetString("lnewDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string loptional {
            get {
                return ResourceManager.GetString("loptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lothers {
            get {
                return ResourceManager.GetString("lothers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Regional Quality Director: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox1 {
            get {
                return ResourceManager.GetString("lothersBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Product Engineering: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox2 {
            get {
                return ResourceManager.GetString("lothersBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Manufacturing Engineering (CCC Manager): Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox3 {
            get {
                return ResourceManager.GetString("lothersBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freigabe Customer: Bezugnehmend auf FTDS-BM-P-008.
        /// </summary>
        internal static string lothersBox4 {
            get {
                return ResourceManager.GetString("lothersBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginn (der Abweichung).
        /// </summary>
        internal static string lperiodBegin {
            get {
                return ResourceManager.GetString("lperiodBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichungsdauer.
        /// </summary>
        internal static string lperiodDevation {
            get {
                return ResourceManager.GetString("lperiodDevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende (der Abweichung).
        /// </summary>
        internal static string lperiodEnd {
            get {
                return ResourceManager.GetString("lperiodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string lposition {
            get {
                return ResourceManager.GetString("lposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drucken.
        /// </summary>
        internal static string lprint {
            get {
                return ResourceManager.GetString("lprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string lproduct {
            get {
                return ResourceManager.GetString("lproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezug.
        /// </summary>
        internal static string lref {
            get {
                return ResourceManager.GetString("lref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe erinnern.
        /// </summary>
        internal static string lremindGroup {
            get {
                return ResourceManager.GetString("lremindGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfrage genehmigt.
        /// </summary>
        internal static string lrequestApproved {
            get {
                return ResourceManager.GetString("lrequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt von.
        /// </summary>
        internal static string lrequestedBy {
            get {
                return ResourceManager.GetString("lrequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfrage abgelehnt.
        /// </summary>
        internal static string lrequestedRejected {
            get {
                return ResourceManager.GetString("lrequestedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risikokategorie.
        /// </summary>
        internal static string lriskCategory {
            get {
                return ResourceManager.GetString("lriskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string lsave {
            get {
                return ResourceManager.GetString("lsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigen.
        /// </summary>
        internal static string lshow {
            get {
                return ResourceManager.GetString("lshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abweichung anzeigen.
        /// </summary>
        internal static string lshowDeviation {
            get {
                return ResourceManager.GetString("lshowDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterschrift.
        /// </summary>
        internal static string lsignature {
            get {
                return ResourceManager.GetString("lsignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung Sollzustand.
        /// </summary>
        internal static string lstandardCondition {
            get {
                return ResourceManager.GetString("lstandardCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string lupdate {
            get {
                return ResourceManager.GetString("lupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Angaben.
        /// </summary>
        internal static string luseAllInputs {
            get {
                return ResourceManager.GetString("luseAllInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warum.
        /// </summary>
        internal static string lwhy {
            get {
                return ResourceManager.GetString("lwhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5  Why um die Ursache des Problems zu finden bzw. aufzuzeigen.
        /// </summary>
        internal static string lwhyBox {
            get {
                return ResourceManager.GetString("lwhyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Make Any Change On This Item Because Its Already Closed !.
        /// </summary>
        internal static string notAllowedToChange {
            get {
                return ResourceManager.GetString("notAllowedToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Update This Item !.
        /// </summary>
        internal static string notAllowedToUpdateItem {
            get {
                return ResourceManager.GetString("notAllowedToUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Select a Line Before making this Action!.
        /// </summary>
        internal static string selectLine {
            get {
                return ResourceManager.GetString("selectLine", resourceCulture);
            }
        }
    }
}
